version: '3.8'

services:
  inventory-database:
    build:
      context: ./inventory-database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - inventory-database:/var/lib/postgresql/data
      - ./inventory-database/scripts/db-inventory:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  inventory-app:
    build:
      context: ./inventory-app
      dockerfile: Dockerfile
    environment:
      - NODE_USER=${NODE_USER}
      - INVENTORY_PORT=${INVENTORY_PORT}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    depends_on:
      inventory-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${INVENTORY_PORT}/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  billing-database:
    build:
      context: ./billing-database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${PG_2_USER}
      - POSTGRES_PASSWORD=${PG_2_PASSWORD}
    volumes:
      - billing-database:/var/lib/postgresql/data
      - ./billing-database/scripts/db-billing:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  
  rabbitmq-server:
    build:
      context: ./rabbitmq-server
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_USER_PWD}
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl authenticate_user ${RABBITMQ_USER} ${RABBITMQ_USER_PWD} || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    expose:
      - "5672"

  billing-app:
    build:
      context: ./billing-app
      dockerfile: Dockerfile
    environment:
      - NODE_USER=${NODE_USER}
      - BILLING_PORT=${BILLING_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - PG_2_DATABASE=${PG_2_DATABASE}
      - PG_2_USER=${PG_2_USER}
      - PG_2_PASSWORD=${PG_2_PASSWORD}
      - PGHOST=${PG_2_HOST}
      - PGPORT=${PGPORT}
    depends_on:
      rabbitmq-server:
        condition: service_healthy
      billing-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BILLING_PORT}/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - NODE_USER=${NODE_USER}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - INVENTORY_API_URL=${INVENTORY_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      inventory-app:
        condition: service_healthy
      rabbitmq-server:
        condition: service_healthy
    volumes:
      - api-gateway:/var/log/api-gateway
    networks:
      - app-network

volumes:
  inventory-database:
      name: inventory-database
  billing-database:
      name: billing-database
  api-gateway:
      name: api-gateway

networks:
  app-network:
